### ISSUE TITLE
Remove vSphere Client

### ISSUE THREAD

**Issue by tezzagriffin** [DDLSTraining/ClassroomServices#1]
Hi Grant, the vSphere Client no longer needs to be installed; if we want it during VMware courses, we'll install the latest one anyway.

**Comment by grantcarthew** [comment]
Done. Thanks mate.

**Comment by grantcarthew** [comment]
AH! it was you Terry how told me to remove this client. This is what caused all the issues with the CiscoLabs site. I was blaming Guy.

**Comment by tezzagriffin** [comment]
Hmm...Seems we might need a list of dependencies for all courses.  We now use the Microsoft RDP client for VMware courses.
Regards Terry

Sent from my Windows 10 phone

________________________________
